describe('Auto test protocommerce',()=>{
    it('Testing book product',()=>{
        cy.visit('https://rahulshettyacademy.com/angularpractice/')
       // cy.wait(500)
        cy.get('.form-control').eq(0).type('azhaguraj')
        //cy.wait(500)
        cy.get(':nth-child(2) > .form-control').type('kpazhaguraj@gmail.com')
        //cy.wait(500)
        cy.get('#exampleInputPassword1').type(12345)
        //cy.wait(500)
        cy.get('#exampleFormControlSelect1').select('Male').should('have.value','Male')
        //cy.wait(500)
        cy.get('#inlineRadio1').check().should('be.checked')
        //cy.wait(500)
        cy.get('#inlineRadio2').check().should('be.checked')
        //cy.wait(500)
        cy.get('#inlineRadio1').should('not.be.checked')
        cy.wait(500)
        cy.get('#inlineRadio3').check({force: true}).should('be.disabled')
        cy.wait(500)
       cy.get("input[type='date']").type('1990-07-28')
       cy.get('.btn').click().should('be.visible')
       cy.get(':nth-child(2) > .nav-link').click()
       cy.get(':nth-child(2) > .card > .card-footer > .btn').click().should('be.visible','Add')
       cy.wait(2000)
       cy.get(':nth-child(1) > .card > .card-footer > .btn').click().should('be.visible','Add') 
       cy.wait(2000)
       cy.get('#navbarResponsive > .navbar-nav > .nav-item > .nav-link').click()
       cy.get(':nth-child(4) > :nth-child(5) > .btn').click()
       cy.get('#country').type('india')
       cy.get('.ng-untouched > .btn').click()
    })
})