describe('Auto Test Protocommerce Site',()=>{
    it('Test Book product',()=>{
        cy.visit('https://rahulshettyacademy.com/angularpractice/')
        cy.get("input[type='text']").eq(0).type('Azhaguraj')
        cy.get('input[name="email"]').type('kpazhaguraj@gmail.com')
        cy.get('#exampleInputPassword1').type(12345)
        cy.get('#exampleCheck1').click()
        cy.get('#exampleFormControlSelect1').select('Female')
        cy.get('#inlineRadio1').check().should('be.checked')
        cy.get('#inlineRadio2').check().should('be.checked')
        cy.get('#inlineRadio1').should('not.be.checked')
        cy.get('#inlineRadio3').check({force: true}).should('be.checked')
        cy.get('input[type="date"]').type('1990-07-28')
        cy.get("input[type='submit']").click()
        cy.get('strong').should('be.visible')
        cy.get('.nav-link').eq(1).click()
        cy.get('.btn.btn-info').eq(0).click()
        cy.get('.btn.btn-info').eq(1).click()
        cy.get('.nav-link.btn.btn-primary').click()
        cy.get(':nth-child(4) > :nth-child(5) > .btn').click()
        cy.get('#country').type('England')
        cy.get('input[type="submit"]').click()
        cy.get('strong').should('be.visible')
        
        })
})